***Rotation finder***

In [3]:
import numpy as np
#Position in transport setup
possdm1 = [[16420,26260],[17120, 28480],[18600,31760],[12060,28640],[24620, 44740],[23780, 41560],[22980, 39580]] #xy positions in the first referential
#Position in the experiment object
possd = [[15760, 26500],[16420, 28780],[17940,32040],[11380,29000],[24300,44820],[23440, 41660],[22560,39720]] #xy positions in the second referential
listeA, listeB = possdm1,possd
H = np.dot(
    np.transpose(np.array(listeA) - np.mean(listeA, axis=0)),
    np.array(listeB) - np.mean(listeB, axis=0),
)
U, S, V = np.linalg.svd(H)
R = np.dot(V, np.transpose(U))
t = np.mean(listeB, axis=0) - np.dot(R, np.mean(listeA, axis=0))
R,t #the rotation and the translation

(array([[ 0.99974618,  0.02252963],
        [-0.02252963,  0.99974618]]),
 array([-1310.81123275,   659.39205642]))

In [4]:
pos = [7820,27200] #To transform a posiion from the first referential
np.dot(R,pos)+t

array([ 7120.00987752, 27676.30630299])